# QUALITY CONTROL OF ADCP DATA

In [1]:
%load_ext autoreload
%autoreload 2
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib
import pandas as pd
import numpy as np

In [15]:
import sys
import os
home_path = os.environ['HOME']
abs_dir = os.path.dirname(os.getcwd())
cwd_path = os.path.join(abs_dir, 'boias', 'axys', 'real_time')
bd_path = os.path.join(abs_dir, 'boias', 'axys', 'bd')
limit_path = os.path.join(abs_dir, 'boias', 'axys', 'limits')
qc_path = os.path.join(abs_dir, 'qc_checks')

In [16]:
sys.path.append(cwd_path)
sys.path.append(bd_path)
sys.path.append(qc_path)
sys.path.append(limit_path)
from bmo_database import *
from bmo_adjust_data import *
import bmo_quality_control as bqc
import ocean_data_qc as qc
import axys_limits as limits

In [78]:
conn = connect_database_remo('PRI')
buoy_id = bmo_on(conn)
id = buoy_id['buoy_id'][0]
last_date_raw = check_last_date(conn, 'bmo_br_current', id)
last_date_raw = last_date_raw[0][0]
time_interval = 24 # hours interval of data to be qualified
bmo_general = get_data_table_db(conn, id, last_date_raw, 'bmo_br_current','ALL')
bmo_general.set_index('date_time', inplace = True)
bmo_general.head()

,buoy_id,id,lat,lon,cspd1,cdir1,cspd2,cdir2,cspd3,cdir3,...,cspd16,cdir16,cspd17,cdir17,cspd18,cdir18,cspd19,cdir19,cspd20,cdir20
date_time,,,,,,,,,,,,,,,,,,,,,
2020-12-04 19:00:00,2,371,-22.8843,-43.1356,-9999.0,-9999,-9999.0,-9999,-9999.0,-9999,...,-9999.0,-9999,-9999.0,-9999,-9999.0,-9999,None,None,None,None
2020-12-08 09:00:00,2,372,-22.8976,-43.1522,-9999.0,-9999,-9999.0,-9999,-9999.0,-9999,...,-9999.0,-9999,-9999.0,-9999,-9999.0,-9999,None,None,None,None
2020-12-08 08:00:00,2,373,-22.8842,-43.1356,-9999.0,-9999,-9999.0,-9999,-9999.0,-9999,...,-9999.0,-9999,-9999.0,-9999,-9999.0,-9999,None,None,None,None
2020-12-08 07:00:00,2,374,-22.8842,-43.1356,-9999.0,-9999,-9999.0,-9999,-9999.0,-9999,...,-9999.0,-9999,-9999.0,-9999,-9999.0,-9999,None,None,None,None
2020-12-08 06:00:00,2,375,-22.8842,-43.1356,-9999.0,-9999,-9999.0,-9999,-9999.0,-9999,...,-9999.0,-9999,-9999.0,-9999,-9999.0,-9999,None,None,None,None

In [79]:
x = list(bmo_general.columns[4:-1])
x[0][0:4] == 'cspd'

True

In [84]:
df = bmo_general.copy()
def definition_flag_pandas_adcp(df):

    flag_data = df [list(df.columns[4:-1])] * 0

    flag_data = flag_data.replace(np.nan, 0).astype(int)

    return flag_data

flag_data = definition_flag_pandas_adcp(df)
# flag_data.head()
parameters = list(df.columns[4:-1])

In [85]:
df

,buoy_id,id,lat,lon,cspd1,cdir1,cspd2,cdir2,cspd3,cdir3,...,cspd16,cdir16,cspd17,cdir17,cspd18,cdir18,cspd19,cdir19,cspd20,cdir20
date_time,,,,,,,,,,,,,,,,,,,,,
2020-12-04 19:00:00,2,371,-22.8843,-43.1356,-9999.0,-9999,-9999.0,-9999,-9999.0,-9999,...,-9999.0,-9999,-9999.0,-9999,-9999.0,-9999,None,None,None,None
2020-12-08 09:00:00,2,372,-22.8976,-43.1522,-9999.0,-9999,-9999.0,-9999,-9999.0,-9999,...,-9999.0,-9999,-9999.0,-9999,-9999.0,-9999,None,None,None,None
2020-12-08 08:00:00,2,373,-22.8842,-43.1356,-9999.0,-9999,-9999.0,-9999,-9999.0,-9999,...,-9999.0,-9999,-9999.0,-9999,-9999.0,-9999,None,None,None,None
2020-12-08 07:00:00,2,374,-22.8842,-43.1356,-9999.0,-9999,-9999.0,-9999,-9999.0,-9999,...,-9999.0,-9999,-9999.0,-9999,-9999.0,-9999,None,None,None,None
2020-12-08 06:00:00,2,375,-22.8842,-43.1356,-9999.0,-9999,-9999.0,-9999,-9999.0,-9999,...,-9999.0,-9999,-9999.0,-9999,-9999.0,-9999,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-04-18 19:00:00,2,3560,-25.5121,-42.7402,0.0,329,0.1,300,0.1,299,...,0.0,329,0.1,300,0.1,299,None,None,None,None
2021-04-18 20:00:00,2,3561,-25.5141,-42.7396,0.0,333,0.0,320,0.1,247,...,0.0,333,0.0,320,0.1,247,None,None,None,None
2021-04-18 21:00:00,2,3562,-25.5160,-42.7382,0.0,317,0.1,258,0.1,252,...,0.0,317,0.1,258,0.1,252,None,None,None,None
2021-04-18 22:00:00,2,3563,-25.5168,-42.7371,0.0,49,0.0,229,0.1,232,...,0.0,49,0.0,229,0.1,232,None,None,None,None
2021-04-18 23:00:00,2,3564,-25.5173,-42.7365,0.0,277,0.0,241,0.2,222,...,0.0,277,0.0,241,0.2,222,None,None,None,None

In [86]:
for parameter in parameters:
    # missing value checks
    if parameter[0:4] == 'cspd':
        df.loc[df[parameter] != -9999, parameter] = df[parameter] * 1000
    flag_data = qc.mis_value_check(df.copy(), limits.mis_value_limits, flag_data.copy(), parameter)
    # coarse range check
    flag_data = qc.range_check(df.copy(), limits.range_limits, flag_data.copy(), parameter)
    # soft range check
    flag_data = qc.range_check_climate(df.copy(), limits.climate_limits, flag_data.copy(), parameter)

> <ipython-input-86-3f3aede6e89d>(5)<module>()
      3     if parameter[0:4] == 'cspd':
      4         breakpoint()
----> 5         if str(df[parameter]) != '-9999.0':
      6             df[parameter] = df[parameter] * 1000
      7     flag_data = qc.mis_value_check(df.copy(), limits.mis_value_limits, flag_data.copy(), parameter)

ipdb> df[parameter]
date_time
2020-12-04 19:00:00   -9999.0
2020-12-08 09:00:00   -9999.0
2020-12-08 08:00:00   -9999.0
2020-12-08 07:00:00   -9999.0
2020-12-08 06:00:00   -9999.0
                        ...
2021-04-18 19:00:00       0.0
2021-04-18 20:00:00       0.0
2021-04-18 21:00:00       0.0
2021-04-18 22:00:00       0.0
2021-04-18 23:00:00       0.0
Name: cspd1, Length: 3191, dtype: float64
ipdb> df[parameter][0]
-9999.0
ipdb> df[parameter][0] == -9999
True
ipdb> exit

BdbQuit:

In [82]:
flag_data = qc.tcontinuityadcpcheck(df.copy(), limits.adcp_limits, 3, flag_data.copy(), ["cspd1", "cdir1"])

In [83]:
df

,buoy_id,id,lat,lon,cspd1,cdir1,cspd2,cdir2,cspd3,cdir3,...,cspd16,cdir16,cspd17,cdir17,cspd18,cdir18,cspd19,cdir19,cspd20,cdir20
date_time,,,,,,,,,,,,,,,,,,,,,
2020-12-04 19:00:00,2,371,-22.8843,-43.1356,-9999000.0,-9999,-9999000.0,-9999,-9999000.0,-9999,...,-9999000.0,-9999,-9999000.0,-9999,-9999000.0,-9999,NaN,NaN,NaN,NaN
2020-12-08 09:00:00,2,372,-22.8976,-43.1522,-9999000.0,-9999,-9999000.0,-9999,-9999000.0,-9999,...,-9999000.0,-9999,-9999000.0,-9999,-9999000.0,-9999,NaN,NaN,NaN,NaN
2020-12-08 08:00:00,2,373,-22.8842,-43.1356,-9999000.0,-9999,-9999000.0,-9999,-9999000.0,-9999,...,-9999000.0,-9999,-9999000.0,-9999,-9999000.0,-9999,NaN,NaN,NaN,NaN
2020-12-08 07:00:00,2,374,-22.8842,-43.1356,-9999000.0,-9999,-9999000.0,-9999,-9999000.0,-9999,...,-9999000.0,-9999,-9999000.0,-9999,-9999000.0,-9999,NaN,NaN,NaN,NaN
2020-12-08 06:00:00,2,375,-22.8842,-43.1356,-9999000.0,-9999,-9999000.0,-9999,-9999000.0,-9999,...,-9999000.0,-9999,-9999000.0,-9999,-9999000.0,-9999,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-04-18 19:00:00,2,3560,-25.5121,-42.7402,0.0,329,100.0,300,100.0,299,...,0.0,329,100.0,300,100.0,299,NaN,NaN,NaN,NaN
2021-04-18 20:00:00,2,3561,-25.5141,-42.7396,0.0,333,0.0,320,100.0,247,...,0.0,333,0.0,320,100.0,247,NaN,NaN,NaN,NaN
2021-04-18 21:00:00,2,3562,-25.5160,-42.7382,0.0,317,100.0,258,100.0,252,...,0.0,317,100.0,258,100.0,252,NaN,NaN,NaN,NaN
2021-04-18 22:00:00,2,3563,-25.5168,-42.7371,0.0,49,0.0,229,100.0,232,...,0.0,49,0.0,229,100.0,232,NaN,NaN,NaN,NaN
2021-04-18 23:00:00,2,3564,-25.5173,-42.7365,0.0,277,0.0,241,200.0,222,...,0.0,277,0.0,241,200.0,222,NaN,NaN,NaN,NaN